name: 'Setup Bin'
description: 'Setup binary tools'
author: 'zcong1993'
branding:
  icon: 'message-square'
  color: 'blue'
inputs:
  name:
    description: 'Bin name'
    required: true
  bin-version:
    description: 'Binary version as cache key'
    required: true
  download-url:
    description: 'Binary download url'
    required: true
  bin-path:
    description: 'Binary file relative path, default ./'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
