name: "build-test"
on: # rebuild any PRs and main branch changes
  push:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: direct url
      uses: ./
      with:
        download-url: https://github.com/zcong1993/changed-files/releases/download/v0.1.2/changed-files_0.1.2_linux_amd64.tar.gz
        name: changed-files
        bin-version: '0.1.2'
        test-cmd: changed-files -v
    - name: test github release
      uses: ./
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: hugo-861
        repo-full: gohugoio/hugo
        tag-version: v0.86.1
        matcher: Linux-64bit.tar.gz$
        test-cmd: hugo version
    - name: test github release latest
      uses: ./
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: hugo
        repo-full: gohugoio/hugo
        tag-version: latest
        matcher: Linux-64bit.tar.gz$
        test-cmd: hugo version
    - name: direct url test cache
      uses: ./
      with:
        download-url: https://github.com/zcong1993/changed-files/releases/download/v0.1.2/changed-files_0.1.2_linux_amd64.tar.gz
        name: changed-files
        bin-version: '0.1.2'
        test-cmd: changed-files -v
